### ISSUE TITLE
missing libcuckoo

### ISSUE THREAD

**Issue by marwaness** [rayrapetyan/shmaps#4]
The libcuckoo headers seem to have been deleted in a previous commit. Building using the official libcuckoo libs fails to build bench and tests.

**Comment by rayrapetyan** [comment]
Please update shmaps from master. Put "libcuckoo" folder from https://github.com/rayrapetyan/libcuckoo (branch bip2) into your include search path. 
Once https://github.com/efficient/libcuckoo/issues/80 is approved, you wouldn't need a custom "libcuckoo" anymore.
Thanks for reporting the issue.

**Comment by rayrapetyan** [comment]
Please check updated README.md.
