### ISSUE TITLE
Unable to compile shmaps with libcuckoo and boost on RHEL7.6

### ISSUE THREAD

**Issue by smrititripathi027** [rayrapetyan/shmaps#5]
[error shmaps.txt](https://github.com/rayrapetyan/shmaps/files/2960662/error.shmaps.txt)

I am compiling sample program of shmaps with libcuckoo and boost version 1.69 but getting compile time error. Error output file is attached.

**Comment by rayrapetyan** [comment]
Please update shmaps from master. Put "libcuckoo" folder from https://github.com/rayrapetyan/libcuckoo (branch bip2) into your include search path. 
Once https://github.com/efficient/libcuckoo/issues/80 is approved, you wouldn't need a custom "libcuckoo" anymore.
Thanks for reporting the issue.

**Comment by smrititripathi027** [comment]
I have already tried what you are suggesting but still I am getting the same errors. Can you please tell which version of boost you are using as I am using boost 1.69. 
Thanks.

**Comment by rayrapetyan** [comment]
I'm also using boost 1.69. Your /opt/libcuckoo-master should be from bip2 branch. 
Which clang (version) do you use?

**Comment by smrititripathi027** [comment]
clang version 5.0.1 (tags/RELEASE_501/final)

**Comment by marwaness** [comment]
@rayrapetyan I am also getting errors while building shmaps after updating from master and replacing libcuckoo with the one you recommend. Attached are the errors.
I am using gcc 6.3 with boost 1.62
[errors.txt](https://github.com/rayrapetyan/shmaps/files/2979017/errors.txt)

**Comment by rayrapetyan** [comment]
Please check updated README.md.
